### ISSUE TITLE
Remove unneeded 

### ISSUE THREAD

**Issue by jiewmeng** [stoyan/cssshrink#1]
Firstly, I'd like to commend you on creating this useful tool. 

I did however notice some possible optimizations. For example, when I have multiple declarations of the same type, it should be possible to remove the previous declarations? 

``` css
a { color: #ff0000; }
a { color: red; }
/* currently results in ... */
a{color:red;color:red}
/* ... but it should be ... */
a{color:red;}
```

Also, if multiple overriding declarations of the same type exists, only the last one need to stay? 

``` css
a { color: red; color: blue; }
/* currently results in ... */
a{color:red;color:blue}
/* ... but it should be ... */
a{color:blue;}
```

**Comment by a5e** [comment]
You forget that it is sometimes necessary to have multiple declarations for fallback purposes.

``` css
a {
  color: red; /* for IE8- which doesn't support rgba */
  color: rgba(255, 0, 0, 0.5); /* for others */
}
```
