### ISSUE TITLE
Prefixed pseudo-classes are not working 

### ISSUE THREAD

**Issue by vincentorback** [stoyan/cssshrink#14]
Hey @stoyan and thanks for this awesome project!

I found a small issue with prefixed pseudo-classes such as `::-webkit-input-placeholder`.

They wont work if they are stacked after each other like this:

``` css
::-webkit-input-placeholder, :-moz-placeholder, ::-moz-placeholder, :-ms-input-placeholder {
  color: red;
}
```

So instead they need to be broken down like this:

``` css
::-webkit-input-placeholder {
  color: red;
}
:-moz-placeholder {
  color: red;
}
::-moz-placeholder {
  color: red;
}
:-ms-input-placeholder {
  color: red;
}
```

Unfortunately I’m not so node-savy yet so i couldn't make a pull-request. But [here’s a jsfiddle](http://jsfiddle.net/vorback/tHhdH/) with the issue. 
This is also the issue with `::selection` but that’s not a CSS standard yet.
