### ISSUE TITLE
Support for IE rules

### ISSUE THREAD

**Issue by dannystyleart** [stoyan/cssshrink#2]
Hello guys,

Not a bad idea, thats kinda feature that I'm using in SASS but I think those code could have been shrinked more.

I've just tried, the web demo and it told me to check my code from the 3340# line where theres only this:

```
filter: alpha(opacity=(30));
```

**Comment by stoyan** [comment]
Can you provide some more info/examples?

I don't get an error when I try

``` css
a {filter: alpha(opacity=(30))}
```

although I think the syntax should be

``` css
a {filter: alpha(opacity=30)}
```
