### ISSUE TITLE
Support multiple values merge

### ISSUE THREAD

**Issue by yisibl** [stoyan/cssshrink#29]
input:

``` css
h1 {
    border: 1px solid red;
    background-color: red;
    background-position: 50% 100%;
}

h1 {
    border: 1px #f00 solid;
    background-color: #f00;
    background-position: center bottom;
}

h1 {
    border: solid 1px rgb(255, 0, 0);
}
```

output:

``` css
h1 {
    border: 1px solid red;
    background-color: red;
    background-position: 50% 100%;
}
```
