### ISSUE TITLE
Fix transparent color replacement

### ISSUE THREAD

**Issue by iamvdo** [stoyan/cssshrink#5]
CSS `transparent` is considered as black transparent, eg `rgba(0,0,0,0)`. So it shouldn't be used for each transparent color.

For example:

``` css
.e {
  background: linear-gradient(rgba(255,255,255,.1), rgba(255,255,255,0));
}
```

gives:

``` css
.e {
  background: linear-gradient(rgba(255,255,255,.1), transparent);
}
```

And that is not the same thing. ;)
